### ISSUE TITLE
DispNetCorr1D always gives negative values

### ISSUE THREAD

**Issue by adhara123007** [lmb-freiburg/flownet2#198] opened 2019-04-05 08:44 UTC
Hi,

This is regarding the DispNet network. I am using the DispNetCorr1D network to register images. I understand the network is only trained to register Right image to the left image. Thus the DispNetCorr1D always gives negative values. In my case, I want to get both positive and negative values of shift. How can I use the weights of the current network to register both Left to Right images and Right to Left images?
For example if I just do 
Left to Right registration
python run-flownet-dispnet.py ../models/DispNetCorr1D/model/DispNetCorr1D_CVPR2016.caffemodel ../models/DispNetCorr1D/model/deploy.prototxt ../data/dispnet/imgL.png ../data/dispnet/imgR.png ../data/dispnet/floLR.flo
![image](https://user-images.githubusercontent.com/40571095/55615310-06ee6900-5787-11e9-8255-1c039213fe15.png)

If I do Right to Left registration

python run-flownet-dispnet.py ../models/DispNetCorr1D/model/DispNetCorr1D_CVPR2016.caffemodel ../models/DispNetCorr1D/model/deploy.prototxt ../data/dispnet/imgR.png ../data/dispnet/imgL.png ../data/dispnet/floRL.flo

![image](https://user-images.githubusercontent.com/40571095/55615319-0e157700-5787-11e9-9f65-014c60887333.png)

In the second case, the disparity map should have been positive.

**Comment by nikolausmayer** [comment] 2019-04-08 11:00
duplicate of https://github.com/lmb-freiburg/dispnet-flownet-docker/issues/14

**Closed by nikolausmayer** 2019-04-08 11:00 UTC
