### ISSUE TITLE
Optical flow blank

### ISSUE THREAD

**Issue by zhanghaozhou** [lmb-freiburg/flownet2#201] opened 2019-05-14 14:10 UTC
@nikolausmayer 
Hi,
I'm testing your codes with the images provided in data examples. However, the output flow for all models are blank with [0,0] for all pixels. I find a similar issue with the same problem but it has not been resolved. Could you please give me some ideas to detect or fix this problem?

Thank you so much!!

Best regards,
Haozhou ZHANG

**Comment by nikolausmayer** [comment] 2019-05-14 14:44
Unfortunately, we do not know the cause of this problem. It might be some weird incompatibility in a specific combination of Nvidia driver, CUDA, and CuDNN, but we have never reproduced the problem on our various setups and we have had a lot of different setups.

We cannot help in this case, sorry.

If you have further information, please feel free to enhance this issue, else I will close it as duplicate of https://github.com/lmb-freiburg/flownet2/issues/93.

**Comment by zhanghaozhou** [comment] 2019-05-18 08:00
@nikolausmayer 
Hi nikolausmayer,

Thank you for your response. According to your advice, I finally solved this problem by changing my CUDA version from 7.5 to 8.0.

Thanks:)

Best regards,
Haozhou

**Closed** 2019-05-20 06:57 UTC
